overrides:
  tmp: ">=0.2.4"
  postcss: ">=8.5.10"
  uuid: ">=11.1.1"
  bs58: "^6.0.0"
  minimatch: "^10.2.3"
  glob: "^11.0.0"
  "babel-plugin-module-resolver>glob": "^8"
  tar: ">=7.5.10"
  "@clerk/shared": "~3.47.4"
  flatted: "~3.4.2"
  lodash: "~4.18.0"
  undici: "~6.24.0"
  picomatch: "~4.0.4"
  "@xmldom/xmldom": "~0.8.12"
  node-forge: "~1.4.0"
  brace-expansion: "~5.0.6"
  yaml: "~2.8.3"
  "@tootallnate/once": "~3.0.1"
  "@clerk/types": "4.101.20"

ignoredBuiltDependencies:
  - "@clerk/shared"
  - browser-tabs-lock
  - bufferutil
  - core-js
  - utf-8-validate

peerDependencyRules:
  allowedVersions:
    react: "18 || 19"
    react-dom: "18 || 19"
