#!/usr/bin/env bash
# HealthBytes Frontend - Environment Setup Script
# Configura automaticamente el .env segun el modo de desarrollo

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
BACKEND_MAIN="$REPO_ROOT/backend/app/main.py"
ENV_FILE="$SCRIPT_DIR/.env"

DEFAULT_CLERK_KEY="pk_test_ZXF1aXBwZWQtc3VuYmlyZC00NC5jbGVyay5hY2NvdW50cy5kZXYk"

print_header() {
  echo ""
  echo "================================================"
  echo "  HealthBytes - Environment Configuration"
  echo "================================================"
  echo ""
}

get_local_ip() {
  local ip=""

  # macOS: prefer route interface IP
  if command -v route >/dev/null 2>&1 && command -v ipconfig >/dev/null 2>&1; then
    local iface
    iface="$(route get default 2>/dev/null | awk '/interface:/{print $2; exit}')"
    if [ -n "${iface:-}" ]; then
      ip="$(ipconfig getifaddr "$iface" 2>/dev/null || true)"
      if [ -n "${ip:-}" ]; then
        echo "$ip"
        return 0
      fi
    fi
  fi

  # Linux/macOS fallback with ifconfig
  if command -v ifconfig >/dev/null 2>&1; then
    ip="$((ifconfig 2>/dev/null || true) | awk '
      /inet / {
        candidate=$2
        if (candidate != "127.0.0.1" && candidate !~ /^169\.254\./ &&
            candidate !~ /^172\.(1[6-9]|2[0-9]|3[01])\./ &&
            candidate !~ /^192\.168\.56\./) {
          print candidate
          exit
        }
      }
    ')"
    if [ -n "${ip:-}" ]; then
      echo "$ip"
      return 0
    fi
  fi

  # Last fallback with hostname
  if command -v hostname >/dev/null 2>&1; then
    ip="$(hostname -I 2>/dev/null | awk '{print $1}' || true)"
    if [ -n "${ip:-}" ]; then
      echo "$ip"
      return 0
    fi
  fi

  return 1
}

read_clerk_key_from_env() {
  local key="$DEFAULT_CLERK_KEY"
  if [ -f "$ENV_FILE" ]; then
    local existing
    existing="$(grep -E '^EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY=' "$ENV_FILE" | head -n 1 | cut -d= -f2- || true)"
    if [ -n "${existing:-}" ]; then
      key="$existing"
    fi
  fi
  echo "$key"
}

update_backend_cors() {
  local local_ip="$1"

  if [ ! -f "$BACKEND_MAIN" ]; then
    echo "⚠️  No se encontro el archivo main.py del backend"
    return 0
  fi

  local tmp_file
  tmp_file="$(mktemp)"

  perl -pe "s#http://(?:10|192\.168|172\.(?:1[6-9]|2\\d|3[01]))\.\d+\.\d+:8081#http://${local_ip}:8081#g; s#exp://(?:10|192\.168|172\.(?:1[6-9]|2\\d|3[01]))\.\d+\.\d+:8081#exp://${local_ip}:8081#g" \
    "$BACKEND_MAIN" > "$tmp_file"

  mv "$tmp_file" "$BACKEND_MAIN"

  echo "✅ CORS del backend actualizado con IP: $local_ip"
  echo ""
  echo "⚠️  IMPORTANTE: Reinicia el backend para aplicar cambios de CORS"
}

print_header

LOCAL_IP=""
if LOCAL_IP="$(get_local_ip)"; then
  echo "✅ Local IP detected: $LOCAL_IP"
else
  echo "⚠️  No se pudo detectar la IP local automaticamente"
  read -r -p "Ingresa tu IP local manualmente (ej: 192.168.1.127): " LOCAL_IP
fi

if [ -z "${LOCAL_IP:-}" ]; then
  echo "❌ No se definio IP local. Abortando."
  exit 1
fi

echo ""
echo "Como vas a usar la aplicacion?"
echo ""
echo "  [1] Solo Web (navegador) - usar localhost"
echo "  [2] Expo Go en celular/tablet - usar IP local ($LOCAL_IP)"
echo "  [3] Ambos (Web + Expo Go) - usar IP local (recomendado)"
echo ""
read -r -p "Selecciona una opcion [1/2/3]: " CHOICE

case "$CHOICE" in
  1)
    API_URL="http://localhost:3001"
    ;;
  2|3)
    API_URL="http://${LOCAL_IP}:3001"
    ;;
  *)
    echo "❌ Opcion invalida. Usando IP local por defecto."
    API_URL="http://${LOCAL_IP}:3001"
    ;;
esac

CLERK_KEY="$(read_clerk_key_from_env)"
NOW="$(date '+%Y-%m-%d %H:%M:%S')"

cat > "$ENV_FILE" <<EOF
# HealthBytes Frontend Environment Variables
# Auto-generated by setup-env.sh on $NOW
# DO NOT commit this file to git

# Backend API URL
EXPO_PUBLIC_API_URL=$API_URL

# Clerk Authentication
EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY=$CLERK_KEY
EOF

echo ""
echo "✅ Archivo .env configurado correctamente"
echo ""
echo "Configuracion aplicada:"
echo "  API URL: $API_URL"
echo ""

read -r -p "Deseas actualizar tambien el CORS del backend? [S/n]: " UPDATE_CORS
UPDATE_CORS="${UPDATE_CORS:-S}"

if [[ "$UPDATE_CORS" =~ ^[Ss]$ ]]; then
  update_backend_cors "$LOCAL_IP"
fi

echo ""
echo "================================================"
echo ""
echo "Proximos pasos:"
echo "  1. Si Expo esta corriendo, presiona 'r' para recargar"
echo "  2. Si no esta corriendo, ejecuta: pnpm start"
if [[ "$UPDATE_CORS" =~ ^[Ss]$ ]]; then
  echo "  3. Reinicia el backend para aplicar CORS"
fi
echo ""
echo "Listo para desarrollar!"
echo ""