#!/usr/bin/env pwsh
# HealthBytes Frontend - Environment Setup Script
# Automatically configures .env based on development mode

$ErrorActionPreference = "Stop"

Write-Host ""
Write-Host "================================================" -ForegroundColor Cyan
Write-Host "  HealthBytes - Environment Configuration" -ForegroundColor Cyan
Write-Host "================================================" -ForegroundColor Cyan
Write-Host ""

# Function to get local IP
function Get-LocalIP {
    try {
        # Get all IPv4 addresses (excluding localhost, VirtualBox, Docker)
        $ips = Get-NetIPAddress -AddressFamily IPv4 | 
               Where-Object { 
                   $_.IPAddress -ne "127.0.0.1" -and 
                   $_.IPAddress -notlike "169.254.*" -and
                   $_.IPAddress -notlike "172.17.*" -and
                   $_.IPAddress -notlike "172.18.*" -and
                   $_.IPAddress -notlike "172.19.*" -and
                   $_.IPAddress -notlike "192.168.56.*"  # VirtualBox
               } | 
               Select-Object -First 1

        if ($ips) {
            return $ips.IPAddress
        }
    } catch {
        Write-Host "⚠️  Error auto-detecting IP" -ForegroundColor Yellow
    }
    
    # Fallback: use ipconfig
    try {
        $ipLine = ipconfig | Select-String -Pattern "IPv4.*192\.168\.\d+\.\d+" | Select-Object -First 1
        if ($ipLine) {
            $ip = $ipLine.Line -replace ".*:\s*", ""
            return $ip.Trim()
        }
    } catch {}
    
    return $null
}

# Detect local IP
$localIP = Get-LocalIP

if ($localIP) {
    Write-Host "✅ Local IP detected: " -NoNewline -ForegroundColor Green
    Write-Host $localIP -ForegroundColor Cyan
} else {
    Write-Host "⚠️  Could not auto-detect local IP" -ForegroundColor Yellow
    $localIP = Read-Host "Enter your local IP manually (e.g.: 192.168.1.127)"
}

Write-Host ""
Write-Host "How will you use the app?" -ForegroundColor Yellow
Write-Host ""
Write-Host "  [1] Web only (browser) - use localhost" -ForegroundColor White
Write-Host "  [2] Expo Go on phone/tablet - use local IP ($localIP)" -ForegroundColor White
Write-Host "  [3] Both (Web + Expo Go) - use local IP (recommended)" -ForegroundColor White
Write-Host ""

$choice = Read-Host "Select option [1/2/3]"

# Determine the API URL
$apiUrl = switch ($choice) {
    "1" { "http://localhost:3001" }
    "2" { "http://${localIP}:3001" }
    "3" { "http://${localIP}:3001" }
    default { 
        Write-Host "❌ Invalid option. Using local IP by default." -ForegroundColor Red
        "http://${localIP}:3001"
    }
}

# Check if .env exists and extract Clerk key
$envFilePath = Join-Path $PSScriptRoot ".env"
$clerkKey = "pk_test_your_publishable_key_here"

if (Test-Path $envFilePath) {
    $envContent = Get-Content $envFilePath -Raw
    # Extract Clerk key if it exists
    if ($envContent -match "EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY=(.+)") {
        $clerkKey = $matches[1].Trim()
    }
}
# Create .env content
$envContent = @"
# HealthBytes Frontend Environment Variables
# Auto-generated by setup-env.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
# DO NOT commit this file to git

# Backend API URL
EXPO_PUBLIC_API_URL=$apiUrl

# Clerk Authentication
EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY=$clerkKey
"@

# Save the .env file
Set-Content -Path $envFilePath -Value $envContent -NoNewline

Write-Host ""
Write-Host "✅ .env file configured successfully" -ForegroundColor Green
Write-Host ""
Write-Host "Configuration applied:" -ForegroundColor Cyan
Write-Host "  API URL: $apiUrl" -ForegroundColor White
Write-Host "  File: $envFilePath" -ForegroundColor White
Write-Host ""

Write-Host "================================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Yellow
Write-Host "  1. If Expo is running, press 'r' to reload" -ForegroundColor White
Write-Host "  2. If not running, execute: pnpm start" -ForegroundColor White
Write-Host ""
Write-Host "✨ Done! Your environment is ready." -ForegroundColor Green
Write-Host ""
Write-Host "¡Listo para desarrollar! 🚀" -ForegroundColor Green
Write-Host ""
