"""Add expo_push_token to users and create reviews table

Revision ID: c4800640e2d3
Revises: a3f1e2d4b5c6
Create Date: 2026-03-17 17:03:20.475609

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app.db.schemas

# revision identifiers, used by Alembic.
revision: str = "c4800640e2d3"
down_revision: Union[str, None] = "a3f1e2d4b5c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reviews",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "product_id", name="uq_user_product_review"),
    )
    op.create_index(op.f("ix_reviews_id"), "reviews", ["id"], unique=False)
    op.create_index(op.f("ix_reviews_product_id"), "reviews", ["product_id"], unique=False)
    op.create_index(op.f("ix_reviews_user_id"), "reviews", ["user_id"], unique=False)
    op.create_index(op.f("ix_cart_items_product_id"), "cart_items", ["product_id"], unique=False)
    op.create_index("idx_order_user_created", "orders", ["user_id", "created_at"], unique=False)
    op.alter_column(
        "payments",
        "status",
        existing_type=postgresql.ENUM(
            "PENDING",
            "PROCESSING",
            "COMPLETED",
            "FAILED",
            "REFUNDED",
            "CANCELLED",
            name="paymentstatus",
        ),
        comment=None,
        existing_comment="Payment status: PENDING, PROCESSING, COMPLETED, FAILED, REFUNDED, CANCELLED",
        existing_nullable=False,
        existing_server_default=sa.text("'PENDING'::paymentstatus"),
    )
    op.alter_column(
        "payments",
        "provider",
        existing_type=postgresql.ENUM("MERCADO_PAGO", name="paymentprovider"),
        comment=None,
        existing_comment="Payment provider: MERCADO_PAGO",
        existing_nullable=False,
    )
    op.create_index("idx_pdt_product", "product_dietary_tags", ["product_id"], unique=False)
    op.create_index("idx_pdt_tag", "product_dietary_tags", ["dietary_tag_id"], unique=False)
    op.alter_column(
        "products",
        "search_vector",
        existing_type=postgresql.TSVECTOR(),
        type_=app.db.schemas.SearchVector(),
        comment=None,
        existing_comment="Full-text search vector for name and description (PostgreSQL tsvector)",
        existing_nullable=True,
    )
    op.add_column("users", sa.Column("expo_push_token", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "expo_push_token")
    op.alter_column(
        "products",
        "search_vector",
        existing_type=app.db.schemas.SearchVector(),
        type_=postgresql.TSVECTOR(),
        comment="Full-text search vector for name and description (PostgreSQL tsvector)",
        existing_nullable=True,
    )
    op.drop_index("idx_pdt_tag", table_name="product_dietary_tags")
    op.drop_index("idx_pdt_product", table_name="product_dietary_tags")
    op.alter_column(
        "payments",
        "provider",
        existing_type=postgresql.ENUM("MERCADO_PAGO", name="paymentprovider"),
        comment="Payment provider: MERCADO_PAGO",
        existing_nullable=False,
    )
    op.alter_column(
        "payments",
        "status",
        existing_type=postgresql.ENUM(
            "PENDING",
            "PROCESSING",
            "COMPLETED",
            "FAILED",
            "REFUNDED",
            "CANCELLED",
            name="paymentstatus",
        ),
        comment="Payment status: PENDING, PROCESSING, COMPLETED, FAILED, REFUNDED, CANCELLED",
        existing_nullable=False,
        existing_server_default=sa.text("'PENDING'::paymentstatus"),
    )
    op.drop_index("idx_order_user_created", table_name="orders")
    op.drop_index(op.f("ix_cart_items_product_id"), table_name="cart_items")
    op.drop_index(op.f("ix_reviews_user_id"), table_name="reviews")
    op.drop_index(op.f("ix_reviews_product_id"), table_name="reviews")
    op.drop_index(op.f("ix_reviews_id"), table_name="reviews")
    op.drop_table("reviews")
    # ### end Alembic commands ###
