"""fix_address_user_id_integer_fk

Revision ID: 35d20be20a0a
Revises: a1b2c3d4e5f6
Create Date: 2026-03-02 13:37:37.090220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '35d20be20a0a'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _column_type_is_integer(table: str, column: str) -> bool:
    """Check if a column is already Integer type."""
    from sqlalchemy import inspect as sa_inspect

    bind = op.get_bind()
    inspector = sa_inspect(bind)
    for col in inspector.get_columns(table):
        if col["name"] == column:
            return str(col["type"]).upper().startswith("INT")
    return False


def upgrade() -> None:
    # Skip if running on a clean DB where the initial migration already
    # created the schema in its final form.
    if _column_type_is_integer("addresses", "user_id"):
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('addresses', 'user_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using='user_id::integer')
    op.create_foreign_key(None, 'addresses', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('idx_cart_items_product_id'), table_name='cart_items')
    op.drop_constraint(op.f('dietary_tags_name_key'), 'dietary_tags', type_='unique')
    op.drop_index(op.f('idx_dietary_tags_name'), table_name='dietary_tags')
    op.create_index(op.f('ix_dietary_tags_id'), 'dietary_tags', ['id'], unique=False)
    op.create_index(op.f('ix_dietary_tags_name'), 'dietary_tags', ['name'], unique=True)
    op.drop_index(op.f('idx_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('idx_order_items_product_id'), table_name='order_items')
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_product_id'), 'order_items', ['product_id'], unique=False)
    op.create_index('idx_order_created_at', 'orders', ['created_at'], unique=False)
    op.create_index('idx_order_status', 'orders', ['status'], unique=False)
    op.drop_column('orders', 'stripe_payment_intent_id')
    # Create enum types first (PostgreSQL requires them to exist before altering columns)
    op.execute("CREATE TYPE paymentcurrency AS ENUM ('CLP', 'USD')")
    op.execute("CREATE TYPE paymentstatus AS ENUM ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'REFUNDED', 'CANCELLED')")
    op.execute("CREATE TYPE paymentprovider AS ENUM ('MERCADO_PAGO')")
    # Alter payments columns: must drop server defaults first to avoid cast mismatch
    op.execute("ALTER TABLE payments ALTER COLUMN currency DROP DEFAULT")
    op.execute("ALTER TABLE payments ALTER COLUMN currency TYPE paymentcurrency USING currency::paymentcurrency")
    op.execute("ALTER TABLE payments ALTER COLUMN currency SET DEFAULT 'CLP'::paymentcurrency")
    op.execute("ALTER TABLE payments ALTER COLUMN status DROP DEFAULT")
    op.execute("ALTER TABLE payments ALTER COLUMN status TYPE paymentstatus USING status::paymentstatus")
    op.execute("ALTER TABLE payments ALTER COLUMN status SET DEFAULT 'PENDING'::paymentstatus")
    op.execute("ALTER TABLE payments ALTER COLUMN provider TYPE paymentprovider USING provider::paymentprovider")
    op.drop_index(op.f('idx_payments_order_id'), table_name='payments')
    op.drop_index(op.f('idx_payments_provider'), table_name='payments')
    op.drop_index(op.f('idx_payments_provider_payment_id'), table_name='payments')
    op.drop_index(op.f('idx_payments_status'), table_name='payments')
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_index(op.f('ix_payments_provider'), 'payments', ['provider'], unique=False)
    op.create_index(op.f('ix_payments_provider_payment_id'), 'payments', ['provider_payment_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.drop_table_comment(
        'payments',
        existing_comment='Payment records for orders via Mercado Pago',
        schema=None
    )
    op.drop_index(op.f('idx_pdt_product'), table_name='product_dietary_tags')
    op.drop_index(op.f('idx_pdt_tag'), table_name='product_dietary_tags')
    op.drop_index(op.f('ix_product_dietary_tags_dietary_tag_id'), table_name='product_dietary_tags')
    op.alter_column('products', 'category',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    # search_vector: SearchVector is a TypeDecorator(impl=Text) that falls back for SQLite.
    # The DB already has TSVECTOR — no actual DDL change needed; skip to avoid import issues.
    op.drop_index(op.f('idx_products_category'), table_name='products')
    op.drop_index(op.f('idx_products_dietary_tags'), table_name='products', postgresql_using='gin')
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.drop_column('products', 'allergens')
    op.drop_column('products', 'dietary_tags')
    op.drop_index(op.f('idx_user_favorites_product_id'), table_name='user_favorites')
    op.drop_index(op.f('idx_user_favorites_user_id'), table_name='user_favorites')
    op.create_index(op.f('ix_user_favorites_id'), 'user_favorites', ['id'], unique=False)
    op.create_index(op.f('ix_user_favorites_product_id'), 'user_favorites', ['product_id'], unique=False)
    op.create_index(op.f('ix_user_favorites_user_id'), 'user_favorites', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # On a clean DB (migrated from 0001_initial), this migration was a no-op,
    # so the downgrade is also a no-op.
    if _column_type_is_integer("addresses", "user_id"):
        # Check if the old-style indexes exist; if not, this was a clean DB — skip
        from sqlalchemy import inspect as sa_inspect
        inspector = sa_inspect(op.get_bind())
        idx_names = [i["name"] for i in inspector.get_indexes("user_favorites")]
        if "ix_user_favorites_user_id" not in idx_names:
            return

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_favorites_user_id'), table_name='user_favorites')
    op.drop_index(op.f('ix_user_favorites_product_id'), table_name='user_favorites')
    op.drop_index(op.f('ix_user_favorites_id'), table_name='user_favorites')
    op.create_index(op.f('idx_user_favorites_user_id'), 'user_favorites', ['user_id'], unique=False)
    op.create_index(op.f('idx_user_favorites_product_id'), 'user_favorites', ['product_id'], unique=False)
    op.add_column('products', sa.Column('dietary_tags', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('allergens', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.create_index(op.f('idx_products_dietary_tags'), 'products', ['dietary_tags'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_products_category'), 'products', ['category'], unique=False)
    # search_vector: no DDL change (see upgrade comment)
    op.alter_column('products', 'category',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.create_index(op.f('ix_product_dietary_tags_dietary_tag_id'), 'product_dietary_tags', ['dietary_tag_id'], unique=False)
    op.create_index(op.f('idx_pdt_tag'), 'product_dietary_tags', ['dietary_tag_id'], unique=False)
    op.create_index(op.f('idx_pdt_product'), 'product_dietary_tags', ['product_id'], unique=False)
    op.create_table_comment(
        'payments',
        'Payment records for orders via Mercado Pago',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_provider_payment_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_provider'), table_name='payments')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.create_index(op.f('idx_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('idx_payments_provider_payment_id'), 'payments', ['provider_payment_id'], unique=False)
    op.create_index(op.f('idx_payments_provider'), 'payments', ['provider'], unique=False)
    op.create_index(op.f('idx_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.alter_column('payments', 'provider',
               existing_type=sa.Enum('MERCADO_PAGO', name='paymentprovider'),
               type_=sa.VARCHAR(length=20),
               comment='Payment provider: MERCADO_PAGO',
               existing_nullable=False,
               postgresql_using='provider::varchar')
    op.alter_column('payments', 'status',
               existing_type=sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'REFUNDED', 'CANCELLED', name='paymentstatus'),
               type_=sa.VARCHAR(length=20),
               comment='Payment status: PENDING, PROCESSING, COMPLETED, FAILED, REFUNDED, CANCELLED',
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::character varying"),
               postgresql_using='status::varchar')
    op.alter_column('payments', 'currency',
               existing_type=sa.Enum('CLP', 'USD', name='paymentcurrency'),
               type_=sa.VARCHAR(length=3),
               existing_nullable=False,
               existing_server_default=sa.text("'CLP'::character varying"),
               postgresql_using='currency::varchar')
    op.execute("DROP TYPE IF EXISTS paymentcurrency")
    op.execute("DROP TYPE IF EXISTS paymentstatus")
    op.execute("DROP TYPE IF EXISTS paymentprovider")
    op.add_column('orders', sa.Column('stripe_payment_intent_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index('idx_order_status', table_name='orders')
    op.drop_index('idx_order_created_at', table_name='orders')
    op.drop_index(op.f('ix_order_items_product_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.create_index(op.f('idx_order_items_product_id'), 'order_items', ['product_id'], unique=False)
    op.create_index(op.f('idx_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.drop_index(op.f('ix_dietary_tags_name'), table_name='dietary_tags')
    op.drop_index(op.f('ix_dietary_tags_id'), table_name='dietary_tags')
    op.create_index(op.f('idx_dietary_tags_name'), 'dietary_tags', ['name'], unique=False)
    op.create_unique_constraint(op.f('dietary_tags_name_key'), 'dietary_tags', ['name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_cart_items_product_id'), 'cart_items', ['product_id'], unique=False)
    op.drop_constraint(None, 'addresses', type_='foreignkey')
    op.alter_column('addresses', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
