from typing import List, Optional

from pydantic import BaseModel, ConfigDict, EmailStr, Field, field_validator


class UserCreate(BaseModel):
    """Schema for user registration - Replica of createUserSchema"""

    email: EmailStr
    password: str = Field(..., min_length=1, max_length=128)
    name: Optional[str] = Field(None, max_length=255)
    address: Optional[str] = None


class UserLogin(BaseModel):
    """Schema for user login - Replica of loginSchema"""

    email: EmailStr
    password: str = Field(..., min_length=1, max_length=128)


class UserUpdate(BaseModel):
    """Schema for user profile update — only user-safe fields.

    Sensitive fields (role, email, is_active) are NOT exposed here
    to prevent mass-assignment privilege escalation.
    """

    password: Optional[str] = Field(None, min_length=1, max_length=128)
    name: Optional[str] = Field(None, max_length=255)
    address: Optional[str] = None
    dietary_preferences: Optional[List[str]] = None


class AdminUserUpdate(UserUpdate):
    """Extended update schema for admins — includes privileged fields."""

    email: Optional[EmailStr] = None
    role: Optional[str] = None


class DietaryPreferencesUpdate(BaseModel):
    """Schema for updating dietary preferences only"""

    tags: List[str] = Field(default_factory=list, description="List of dietary tag slugs")


class PushTokenUpdate(BaseModel):
    """Schema for updating Expo push notification token"""

    token: str = Field(..., min_length=1, max_length=255)

    @field_validator("token")
    @classmethod
    def validate_expo_push_token(cls, value: str) -> str:
        """Accept only Expo push token formats generated by Expo clients."""
        valid_prefixes = ("ExponentPushToken[", "ExpoPushToken[")
        has_valid_wrapper = any(
            value.startswith(prefix) and value.endswith("]") and len(value) > len(prefix) + 1
            for prefix in valid_prefixes
        )
        if not has_valid_wrapper:
            raise ValueError("Invalid Expo push token")
        return value


class UserResponse(BaseModel):
    """User response schema (without password)"""

    id: int
    email: str
    role: str
    name: Optional[str]
    address: Optional[str]
    dietary_preferences: List[str] = Field(default_factory=list)

    model_config = ConfigDict(from_attributes=True)


class Token(BaseModel):
    """Token response"""

    token: str
    refresh_token: str


class TokenRefresh(BaseModel):
    """Schema for token refresh request"""

    refresh_token: str


class UserWithToken(BaseModel):
    """User registration/login response"""

    user: UserResponse
    token: str
    refresh_token: str
